Sentry error logging 181255231
NHMDenmark/OpenCollections pull request #160
Opened 2022-02-21 12:48 UTC by sotiriosa-cogapp

Link to PT: https://www.pivotaltracker.com/story/show/181255231

2022-02-22 16:41 UTC, neilh-cogapp requested changes
A few comments to address please @sotiriosa-cogapp - but on the whole this looks good. Thanks!

2022-02-22 16:41 UTC, neilh-cogapp commented on .gitignore
> +.sentryclirc
I think the tool added this twice!

2022-02-22 16:41 UTC, neilh-cogapp commented on next.config.wizardcopy.js
> +module.exports = withSentryConfig(moduleExports, sentryWebpackPluginOptions);
Do we need this `wizardcopy` file still?

2022-02-22 16:41 UTC, neilh-cogapp commented on pages/_error.js
> +export default MyError;
Not exactly sure what this component does? If it's an example generated by the wizard should we implement it, or add it as an example to the docs perhaps?

Keen to hear your thoughts.

2022-02-22 16:41 UTC, neilh-cogapp commented on pages/search.js
> +      </button>
Is this a bit like @lukew-cogapp's "DO NOT CLICK THIS BUTTON"?

2022-02-23 10:14 UTC, sotiriosa-cogapp commented on pages/_error.js
> +export default MyError;
The component is created as part of the Sentr/Next wizard (see the Create a Custom _error Page section here: https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/). It's purpose is to ape/replace the built in Next error page so that the detail can be captured in Sentry.
I think we're best leaving it in place.

2022-02-23 10:15 UTC, sotiriosa-cogapp commented on pages/search.js
> +      </button>
haha, whoops

2022-02-23 10:59 UTC, neilh-cogapp commented on pages/_error.js
> +export default MyError;
Thanks. Could I ask that we rename it from `MyError` to something like `CustomError` or `SentryError`?

2022-02-24 09:39 UTC, merged