#184711389 - Handle incorrect GBIF keys
NHMDenmark/OpenCollections pull request #179
Opened 2023-03-31 13:44 UTC by nitinl-cogapp

[#184711389 - Handle incorrect GBIF keys](https://www.pivotaltracker.com/story/show/184711389)

- Fixes page error if a GBIF slug can't be matched.
- Adds GitHub action to flag to Slack if a GBIF key is invalid.
- Fixes some console errors on 404 page.

Note: the action requires a secret to be added to the repo under the `SLACK_WEBHOOK` key.

2023-03-31 15:26 UTC, neilh-cogapp requested changes
These changes looks good, but I think we should use the https://github.com/slackapi/slack-github-action rather than `curl` to a new Webhook.

2023-03-31 16:48 UTC, nitinl-cogapp commented on .github/workflows/data-checks.yaml
> +          fi
Fair, added in https://github.com/NHMDenmark/OpenCollections/pull/179/commits/74810d1fabeb6d02fa29221988b39d0bbb6a18b7

2023-04-03 09:36 UTC, neilh-cogapp reviewed
This looks great, one final suggestion made, but otherwise ready for merge.

2023-04-03 09:36 UTC, neilh-cogapp commented on .github/workflows/data-checks.yaml
> +  schedule:
One final suggestion, for all Workflows that use a cron schedule, I generally add a `workflow_dispatch:` trigger. This will enable the action to run on demand via the Actions tab. Useful for debugging, testing and ad-hoc runs.

```suggestion
  workflow_dispatch:
  schedule:
```

2023-04-03 09:36 UTC, neilh-cogapp approved these changes

2023-04-03 09:41 UTC, nitinl-cogapp commented
@neilh-cogapp nice catch on the ad-hoc triggering, I've added that & also fixed the title case for Botany. It was missing a translation key-val.

2023-04-03 09:42 UTC, neilh-cogapp commented
Brill - thanks.

2023-04-03 09:43 UTC, merged